export const TOGGLE_APP_DRAWER = 'TOGGLE_APP_DRAWER';
export const SET_LOADING = 'SET_LOADING';
export const SHOW_SUCCESS_MSG = 'SHOW_SUCCESS_MSG';
export const SHOW_ERROR_MSG = 'SHOW_ERROR_MSG';
export const SHOW_WARNING_MSG = 'SHOW_WARNING_MSG';
export const RESET_SNACKBAR = 'RESET_SNACKBAR';
// export cosnt SHOW
